POST https://lincut.herokuapp.com/user/register
Content-Type: application/json


{
    "name":"Solomon",
    "password":"solomon",
    "email":"sa@gmail.com"
}
###
POST https://lincut.herokuapp.com/user/login
Content-Type: application/json


{
        "email":"solo@gmail.com",
    "password":"aaaa"
}
###
PATCH https://lincut.herokuapp.com/user/5fe24aab5aff091f18eebae4
Content-Type: application/json


{
    "password":"Sanusi"
}

###
GET  https://lincut.herokuapp.com/user/5fe24aab5aff091f18eebae4
###
GET  https://lincut.herokuapp.com/user/url/5fe24aab5aff091f18eebae4
###
POST https://lincut.herokuapp.com/5fe65776a879830e9cf48494
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTY1Nzc2YTg3OTgzMGU5Y2Y0ODQ5NCIsImlhdCI6MTYwOTE4OTkzOCwiZXhwIjoxNjA5MTkzNTM4fQ.nk7VNCnESVmX5br6xGin09FMq3LaPu4V1puCwXd8cJ4


{
    "fullUrl":"www.youtube.com"
    
}
###
GET https://lincut.herokuapp.com/user/5fe65776a879830e9cf48494
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTY1Nzc2YTg3OTgzMGU5Y2Y0ODQ5NCIsImlhdCI6MTYwOTE4OTkzOCwiZXhwIjoxNjA5MTkzNTM4fQ.nk7VNCnESVmX5br6xGin09FMq3LaPu4V1puCwXd8cJ4


###
PATCH  https://lincut.herokuapp.com/5fe256cdaec298238857049e
Content-Type: application/json


{
    "fullUrl":"www.netlify.app"
    
}

###
DELETE https://lincut.herokuapp.com/5fe256cdaec298238857049e